// Drives `viewer/rigid-body.js` outside a browser and prints one JSON blob.
// The module imports nothing, so this is the whole harness (contrast
// `ground_harness.mjs`).
//
// argv[2] is the path to `tests/fixtures/` (read directly, not copied
// alongside the module -- same reasoning as `gait_select_harness.mjs`):
// `rigid_body_golden.json` is generated by `make_rigid_body_golden.py` from a
// pure-Python copy of the reference `Model`
// (`vehicle-collision-physics/tools/emulator/r2_node_test_lib.py`, verified
// there against the game server's own machine code). Each scenario is a
// tiny op list -- `addAccelerationAt`, `addAcceleration`, `addFrictionAt`,
// `translate`, `wake`, `setSleepiness`, direct `setV`/`setW`/`setAcc`/
// `setRacc`/`setFr`/`setRfr` pokes, `step`, `tangentSpeed`, `reset` -- and
// this harness replays the identical list against the real `RigidBody`,
// recording one snapshot (or, for `tangentSpeed`, the returned vector) per
// op. `test_rigid_body.py` diffs the two traces to 1e-9.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  RigidBody, staticBody, boxInertia,
  TICK, GRAVITY, FRAMES_BEFORE_SLEEP,
  ACCEL_CLAMP_LIMIT_SQ, ACCEL_CLAMP_SPEED,
  POSITIONAL_FRICTION_ZERO_SQ, ROTATIONAL_FRICTION_ZERO_SQ,
  WAKE_ACCEL_SQ, WAKE_LINEAR_SPEED_SQ, WAKE_ANGULAR_SPEED_SQ,
  ROTATION_THRESHOLD_SQ, FALLBACK_INERTIA, STATIC_MASS,
} from './rigid-body.mjs';

function snapshot(b) {
  return {
    pos: [...b.pos], axes: b.axes.map(r => [...r]),
    v: [...b.v], w: [...b.w],
    acc: [...b.acc], racc: [...b.racc],
    fr: [...b.fr], rfr: [...b.rfr],
    n: b.frictionSamples, sleepiness: b.sleepiness,
  };
}

function applyOp(b, op) {
  switch (op.op) {
    case 'step': b.step(op.dt ?? TICK); return snapshot(b);
    case 'addAccelerationAt': b.addAccelerationAt(op.p, op.a); return snapshot(b);
    case 'addAcceleration': b.addAcceleration(op.a); return snapshot(b);
    case 'addFrictionAt': b.addFrictionAt(op.p, op.f); return snapshot(b);
    case 'translate': b.translate(op.dp); return snapshot(b);
    case 'wake': b.wake(); return snapshot(b);
    case 'setSleepiness': b.setSleepiness(op.n); return snapshot(b);
    case 'setV': b.v[0] = op.v[0]; b.v[1] = op.v[1]; b.v[2] = op.v[2]; return snapshot(b);
    case 'setW': b.w[0] = op.w[0]; b.w[1] = op.w[1]; b.w[2] = op.w[2]; return snapshot(b);
    case 'setAcc': b.acc[0] = op.acc[0]; b.acc[1] = op.acc[1]; b.acc[2] = op.acc[2]; return snapshot(b);
    case 'setRacc': b.racc[0] = op.racc[0]; b.racc[1] = op.racc[1]; b.racc[2] = op.racc[2]; return snapshot(b);
    case 'setFr': b.fr[0] = op.fr[0]; b.fr[1] = op.fr[1]; b.fr[2] = op.fr[2]; return snapshot(b);
    case 'setRfr': b.rfr[0] = op.rfr[0]; b.rfr[1] = op.rfr[1]; b.rfr[2] = op.rfr[2]; return snapshot(b);
    case 'reset': b.reset({ position: op.position, axes: op.axes }); return snapshot(b);
    case 'tangentSpeed': return { tangent: b.tangentSpeed(op.p, [0, 0, 0]) };
    default: throw new Error(`unknown op ${op.op}`);
  }
}

const fixturesDir = process.argv[2];
const golden = JSON.parse(readFileSync(join(fixturesDir, 'rigid_body_golden.json'), 'utf8'));

const scenarios = {};
for (const s of golden.scenarios) {
  const body = new RigidBody(s.init);
  scenarios[s.name] = s.ops.map(op => applyOp(body, op));
}

// --- API surface the golden replay above does not reach ------------------
const api = {};

api.constants = {
  TICK, GRAVITY, FRAMES_BEFORE_SLEEP,
  ACCEL_CLAMP_LIMIT_SQ, ACCEL_CLAMP_SPEED,
  POSITIONAL_FRICTION_ZERO_SQ, ROTATIONAL_FRICTION_ZERO_SQ,
  WAKE_ACCEL_SQ, WAKE_LINEAR_SPEED_SQ, WAKE_ANGULAR_SPEED_SQ,
  ROTATION_THRESHOLD_SQ, FALLBACK_INERTIA, STATIC_MASS,
};

api.boxInertia = boxInertia(2, 3, 4); // [(9+16)/3, (16+4)/3, (4+9)/3]

// A fresh body is born awake, at rest, with a zero accumulator (no gravity
// seeded yet) -- constructor contract, spec §4.2.
{
  const b = new RigidBody({ box: [1, 1, 1], position: [1, 2, 3] });
  api.freshBody = {
    mass: b.mass, isStatic: b.isStatic, sleeping: b.sleeping,
    pos: [...b.pos], v: [...b.v], w: [...b.w], acc: [...b.acc],
    sleepiness: b.sleepiness,
  };
}

// `translate` is an immediate positional correction: no accumulator, no
// clamp, no drag, no sleep gate -- works even on a body forced asleep.
{
  const b = new RigidBody({ box: [1, 1, 1], position: [0, 0, 0] });
  b.setSleepiness(0);
  b.translate([1, 2, 3]);
  api.translateOnSleepingBody = { pos: [...b.pos], sleeping: b.sleeping, v: [...b.v] };
}

// `wake()` only resets the countdown -- nothing else moves.
{
  const b = new RigidBody({ box: [1, 1, 1] });
  b.setSleepiness(0);
  b.wake();
  api.wakeOnlyTouchesSleepiness = { sleepiness: b.sleepiness, sleeping: b.sleeping, v: [...b.v] };
}

// `sleeping` getter tracks the <=0 rule directly.
{
  const b = new RigidBody({ box: [1, 1, 1] });
  const beforeAtOne = (b.setSleepiness(1), b.sleeping);
  const atZero = (b.setSleepiness(0), b.sleeping);
  const negative = (b.setSleepiness(-1), b.sleeping);
  api.sleepingGetter = { beforeAtOne, atZero, negative };
}

// `dragHook`: called on an awake root, before the linear step -- so a hook
// that adds an acceleration is subject to the same clamp/integration as any
// other force.
{
  const calls = [];
  const b = new RigidBody({ box: [1, 1, 1], gravityModifier: 0 });
  b.dragHook = (body, dt) => { calls.push({ dt, accBefore: [...body.acc] }); body.addAcceleration([9, 0, 0]); };
  b.step();
  api.dragHook = { calls, vAfter: [...b.v] };
  // Never called while asleep.
  const b2 = new RigidBody({ box: [1, 1, 1] });
  b2.setSleepiness(0);
  let called = false;
  b2.dragHook = () => { called = true; };
  b2.step();
  api.dragHookSkippedWhileAsleep = called;
}

// The geometry-less fallback is selected purely by `box: null`, at
// construction, independent of what forces are ever posted.
{
  const withBox = new RigidBody({ box: [1, 1, 1] });
  const withoutBox = new RigidBody({ box: null });
  api.hasGeometryFlag = { withBox: withBox.hasGeometry, withoutBox: withoutBox.hasGeometry };
}

// `staticBody`: no-op adders, fixed sleeping/mass, zero tangentSpeed.
{
  const s = staticBody({ position: [5, 6, 7] });
  s.addAccelerationAt([0, 0, 0], [10, 10, 10]);
  s.addAcceleration([10, 10, 10]);
  s.addFrictionAt([0, 0, 0], [10, 10, 10]);
  const out = [0, 0, 0];
  s.tangentSpeed([100, 100, 100], out);
  api.staticBody = {
    mass: s.mass, isStatic: s.isStatic, sleeping: s.sleeping,
    pos: [...s.pos], v: [...s.v], w: [...s.w],
    tangentSpeedResult: [...out],
  };
}

process.stdout.write(JSON.stringify({ scenarios, api }));
