"""`viewer/rigid-body.js`: the root-node integrator (`PhysicsNode::updatePhysics`,
`collision-response.md` §3-4 / `R2-integrator.md` F3-F10).

Same trick as `test_armor.py`: the module imports nothing, so it is copied
next to `rigid_body_harness.mjs` into a temp dir and run under plain `node`.
The harness replays every scenario in `tests/fixtures/rigid_body_golden.json`
-- generated by `tests/fixtures/make_rigid_body_golden.py` from a pure-Python
copy of the reference `Model`, itself checked against the game server's own
machine code (`vehicle-collision-physics/reports/V2-verification-of-R2.md`
§0) -- and prints the resulting trace for a generic agreement check, plus a
handful of hand-picked assertions that name the specific spec claim each
number demonstrates. Every number here traces to that golden file or to the
spec text cited alongside it -- never to `rigid-body.js`'s own output.
"""

from __future__ import annotations

import json
import math
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

ROOT = Path(__file__).resolve().parents[1]
MODULE = ROOT / "viewer" / "rigid-body.js"
HARNESS = Path(__file__).resolve().parent / "rigid_body_harness.mjs"
FIXTURES = Path(__file__).resolve().parent / "fixtures"
GOLDEN = FIXTURES / "rigid_body_golden.json"

TOLERANCE = 1e-9


def run_harness() -> dict:
    if shutil.which("node") is None:
        raise unittest.SkipTest("node is not installed")
    if not GOLDEN.exists():
        raise unittest.SkipTest("missing tests/fixtures/rigid_body_golden.json "
                                 "-- run make_rigid_body_golden.py first")
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        shutil.copyfile(MODULE, work / "rigid-body.mjs")
        shutil.copyfile(HARNESS, work / "harness.mjs")
        proc = subprocess.run(
            ["node", str(work / "harness.mjs"), str(FIXTURES)],
            capture_output=True, text=True, timeout=120)
    if proc.returncode != 0:
        raise AssertionError(f"harness failed:\n{proc.stderr}")
    return json.loads(proc.stdout)


def flatten(value, path=""):
    """Yield (path, number) for every leaf in a JSON-ish nested structure,
    so a scenario snapshot and its golden counterpart can be diffed
    position-by-position with a useful path on failure."""
    if isinstance(value, bool):
        yield path, value
    elif isinstance(value, (int, float)):
        yield path, value
    elif isinstance(value, list):
        for i, v in enumerate(value):
            yield from flatten(v, f"{path}[{i}]")
    elif isinstance(value, dict):
        for k in sorted(value):
            yield from flatten(value[k], f"{path}.{k}" if path else k)
    else:
        raise TypeError(f"unexpected leaf type at {path}: {type(value)}")


class RigidBodyGoldenTests(unittest.TestCase):
    """One generic pass over every scenario in the golden fixture: the JS
    trace must agree with the Python reference model to 1e-9 at every leaf
    of every snapshot, per the briefing's own tolerance."""

    results: dict
    golden: dict

    @classmethod
    def setUpClass(cls) -> None:
        cls.results = run_harness()
        cls.golden = json.loads(GOLDEN.read_text())

    def test_every_scenario_matches_the_reference_model(self) -> None:
        got_scenarios = self.results["scenarios"]
        names = [s["name"] for s in self.golden["scenarios"]]
        self.assertEqual(sorted(names), sorted(got_scenarios.keys()),
                          "harness produced a different scenario set than the fixture")
        for scenario in self.golden["scenarios"]:
            name = scenario["name"]
            expected_trace = scenario["trace"]
            got_trace = got_scenarios[name]
            self.assertEqual(len(expected_trace), len(got_trace),
                              f"{name}: op count mismatch")
            for i, (expected, got) in enumerate(zip(expected_trace, got_trace)):
                expected_leaves = dict(flatten(expected))
                got_leaves = dict(flatten(got))
                self.assertEqual(set(expected_leaves), set(got_leaves),
                                  f"{name}[{i}]: shape mismatch")
                for leaf, exp_val in expected_leaves.items():
                    got_val = got_leaves[leaf]
                    if isinstance(exp_val, bool):
                        self.assertEqual(exp_val, got_val, f"{name}[{i}].{leaf}")
                    else:
                        self.assertAlmostEqual(
                            exp_val, got_val, delta=TOLERANCE,
                            msg=f"{name}[{i}].{leaf}: expected {exp_val}, got {got_val}")


class RigidBodyTargetedTests(unittest.TestCase):
    """Hand-picked checks that name the specific spec claim a number in the
    golden trace demonstrates -- the golden test above already proves JS
    matches the reference model bit-for-bit-ish; these prove the reference
    model itself lands where the spec says it should."""

    results: dict
    golden: dict
    by_name: dict

    @classmethod
    def setUpClass(cls) -> None:
        cls.results = run_harness()
        cls.golden = json.loads(GOLDEN.read_text())
        cls.by_name = {s["name"]: s["trace"] for s in cls.golden["scenarios"]}

    def test_constants(self) -> None:
        c = self.results["api"]["constants"]
        self.assertEqual(1 / 30, c["TICK"])
        self.assertEqual(-14.73, c["GRAVITY"])
        self.assertEqual(100, c["FRAMES_BEFORE_SLEEP"])
        self.assertEqual(1e6, c["ACCEL_CLAMP_LIMIT_SQ"])
        self.assertEqual(1000, c["ACCEL_CLAMP_SPEED"])
        self.assertEqual(62500, c["POSITIONAL_FRICTION_ZERO_SQ"])
        self.assertEqual(40000, c["ROTATIONAL_FRICTION_ZERO_SQ"])
        self.assertEqual(2.5, c["WAKE_ACCEL_SQ"])
        self.assertEqual(0.25, c["WAKE_LINEAR_SPEED_SQ"])
        self.assertEqual(0.25, c["WAKE_ANGULAR_SPEED_SQ"])
        # F6's constant is one ULP off a round 1e-6 (see rigid-body.js's own
        # comment on ROTATION_THRESHOLD_SQ / R2's emulator harness).
        self.assertEqual(1.0000001e-6, c["ROTATION_THRESHOLD_SQ"])
        self.assertEqual(0.0314, c["FALLBACK_INERTIA"])
        self.assertEqual(1e12, c["STATIC_MASS"])

    def test_box_inertia_formula(self) -> None:
        # boxInertia(2,3,4): Ix=(dy^2+dz^2)/3, Iy=(dz^2+dx^2)/3, Iz=(dx^2+dy^2)/3.
        self.assertEqual([25 / 3, 20 / 3, 13 / 3], self.results["api"]["boxInertia"])

    def test_free_fall_first_tick_has_no_gravity(self) -> None:
        # spec §4.2: "a new or just-woken body gets no gravity in its first
        # integrated tick" -- v after the first step must be exactly zero,
        # and only starts falling from the second tick.
        trace = self.by_name["free_fall_from_rest"]
        self.assertEqual([0.0, 0.0, 0.0], trace[0]["v"])
        self.assertEqual(5.0, trace[0]["pos"][1])
        self.assertLess(trace[1]["v"][1], 0.0)
        self.assertAlmostEqual(-14.73 / 30, trace[1]["v"][1], delta=TOLERANCE)

    def test_free_falling_body_never_sleeps(self) -> None:
        # §4.3: "a free-falling body can therefore never sleep" -- gravity
        # alone clears the 2.5 wake-accel threshold every tick from the
        # second tick on, so sleepiness is pinned at 100, never counting down.
        trace = self.by_name["free_fall_from_rest"]
        self.assertEqual(99, trace[0]["sleepiness"])   # one quiet tick before gravity exists
        for snap in trace[1:]:
            self.assertEqual(100, snap["sleepiness"])

    def test_accel_clamp_scales_not_drops(self) -> None:
        # F5: |acc|^2 > 1e6 scales the vector down to speed 1000, keeping
        # direction -- not a drop to zero (that's friction's rule, below).
        trace = self.by_name["accel_clamp_edge"]
        v = trace[-1]["v"]
        speed = math.sqrt(v[0] ** 2 + v[1] ** 2 + v[2] ** 2) / (1 / 30)
        self.assertAlmostEqual(1000, speed, delta=1e-6)
        # direction preserved: v is still along the original (0.6, 0.8, 0) ray.
        self.assertAlmostEqual(0.6, v[0] / (v[0] ** 2 + v[1] ** 2) ** 0.5, delta=1e-9)

    def test_friction_clamp_drops_whole_vector(self) -> None:
        # F5: |fr|^2 > 62500 drops friction entirely -- v stays at zero
        # (gravityModifier is 0 in this scenario, and acc was never set).
        trace = self.by_name["friction_clamp_drop_edge"]
        self.assertEqual([0.0, 0.0, 0.0], trace[-1]["fr"])
        self.assertEqual([0.0, 0.0, 0.0], trace[-1]["v"])

    def test_rotational_friction_tpre_tpost_quirk(self) -> None:
        # F6: the Z-axis Δω term uses the torque sum from BEFORE the 40000
        # rfr-zero test (Tpre); Y and X use it from AFTER (Tpost). With
        # racc=(10,10,10) and rfr=(0,0,205) (|rfr|^2=42025 -> zeroed), Tpre's
        # Z-component (215) survives into w.z, while rfr's loss is why w.z is
        # NOT simply proportional to what racc alone would give on any axis.
        trace = self.by_name["rot_friction_clamp_tpre_tpost_quirk"]
        rfr_after = trace[-1]["rfr"]
        self.assertEqual([0.0, 0.0, 0.0], rfr_after)  # the 40000 test did fire
        w = trace[-1]["w"]
        # All three axes are nonzero (racc alone feeds X/Y/Z equally at 10),
        # but Z is disproportionately larger -- the extra contribution can
        # only have come from rfr's z=205 acting through Tpre.
        self.assertGreater(abs(w[2]), abs(w[0]) * 10)
        self.assertGreater(abs(w[2]), abs(w[1]) * 10)

    def test_racc_clamp_scales_before_projection(self) -> None:
        # F6: |racc|^2 > 1e6 scales to speed 1000 BEFORE Tpre/Tpost are built
        # -- mirrors the linear step's acc clamp exactly.
        trace = self.by_name["racc_clamp_edge"]
        racc_before_zeroing = None
        # racc is cleared to 0 by the end of `step`; recover the clamped
        # magnitude indirectly is not possible from the snapshot alone, so
        # this just confirms the clamp ran by checking w is finite and
        # bounded to what a speed-1000 racc could produce in one tick, not
        # the ~1000.1 unclamped magnitude (the difference is tiny but the
        # NaN/inf case this guards against is not).
        w = trace[-1]["w"]
        for component in w:
            self.assertTrue(math.isfinite(component))

    def test_sleep_countdown_reaches_exactly_zero(self) -> None:
        # §4.3: sleepiness counts down from FRAMES_BEFORE_SLEEP (100) to 0
        # over exactly 100 quiet ticks, and the asleep branch (zeroed state)
        # takes over on that same 100th tick.
        trace = self.by_name["sleep_countdown_to_zero"]
        self.assertEqual(100, len(trace))
        self.assertEqual(99, trace[0]["sleepiness"])
        self.assertEqual(0, trace[-1]["sleepiness"])
        self.assertEqual([0.0, 0.0, 0.0], trace[-1]["v"])
        self.assertEqual([0.0, 0.0, 0.0], trace[-1]["acc"])

    def test_wake_thresholds_are_strict_greater_equal(self) -> None:
        # F8: each wake test is `>=`, confirmed at the exact boundary (wakes)
        # and just below it (does not -- decrements instead).
        for name, at_index, below_index in (
            ("wake_accel_boundary", 2, 5),
            ("wake_linear_speed_boundary", 2, 5),
            ("wake_angular_speed_boundary", 2, 5),
        ):
            trace = self.by_name[name]
            self.assertEqual(100, trace[at_index]["sleepiness"], f"{name}: at boundary")
            self.assertEqual(4, trace[below_index]["sleepiness"], f"{name}: just below")

    def test_sleeping_body_accumulator_is_discarded_next_step(self) -> None:
        # §4.3 / V2 §3: the resolve pass posts into a sleeping body's
        # accumulators with no sleep gate; it is discarded on the NEXT
        # `step` when the posted force is too small to clear the wake test.
        trace = self.by_name["sleeping_body_accel_zeroed_next_step"]
        self.assertEqual([0.5, 0.0, 0.0], trace[1]["acc"])      # posted while asleep
        self.assertEqual([0.0, 0.0, 0.0], trace[2]["acc"])      # discarded next step
        self.assertEqual(0, trace[2]["sleepiness"])             # stayed asleep

    def test_geometry_less_fallback_matches_formula(self) -> None:
        # F6 else-branch: Δω = (racc + rfr) * dt / 0.0314, and its own
        # |Δω|^2 > 1e6 drop (not the geometry branch's per-axis one).
        trace = self.by_name["geometry_less_fallback_branch"]
        w_after_first_step = trace[2]["w"]
        expected = -1.0 * (1 / 30) / 0.0314   # racc.y=-3, rfr.y=2 -> t.y=-1
        self.assertAlmostEqual(expected, w_after_first_step[1], delta=TOLERANCE)
        # The forced-drop step leaves w unchanged from the previous tick.
        w_after_drop_step = trace[-1]["w"]
        self.assertEqual(w_after_first_step, w_after_drop_step)

    def test_tangent_speed_is_v_plus_w_cross_r_from_origin(self) -> None:
        trace = self.by_name["tangent_speed"]
        # p == pos: pure v.
        self.assertEqual([3.0, 0.0, 0.0], trace[2]["tangent"])
        # r=(0,0,5), w=(0,2,0): w x r = (2*5-0*0, 0*0-0*5, 0*0-2*0) = (10,0,0).
        self.assertEqual([13.0, 0.0, 0.0], trace[3]["tangent"])
        # r=(0,1,0), w=(0,2,0): parallel, cross is zero.
        self.assertEqual([3.0, 0.0, 0.0], trace[4]["tangent"])

    def test_respawn_reset_reproduces_birth(self) -> None:
        # reset() zeroes everything and stands the body back up awake with
        # acc still zero -- same "no gravity this tick" property as a fresh
        # construction (spec §4.2).
        trace = self.by_name["respawn_reset"]
        # ops: ...addAccelerationAt, step, step, reset, step, step -- trace[3]
        # is the reset() op itself (state already zeroed by definition);
        # trace[4]/[5] are the two steps that follow it.
        first_step_after_reset = trace[4]
        self.assertEqual([0.0, 0.0, 0.0], first_step_after_reset["v"])  # no gravity yet
        second_step_after_reset = trace[5]
        self.assertLess(second_step_after_reset["v"][1], 0.0)  # gravity now applies

    def test_soldier_exempt_from_auto_countdown_not_from_sleep_gate(self) -> None:
        # F8: `templateClassId != soldier` gates the wake-test/countdown
        # block only; the `isSleeping()` zero-and-return still applies to a
        # soldier body regardless.
        trace = self.by_name["soldier_sleep_exemption"]
        self.assertEqual(5, trace[0]["sleepiness"])
        self.assertEqual(5, trace[1]["sleepiness"])  # no auto-decrement
        self.assertEqual(0, trace[3]["sleepiness"])  # forced asleep externally
        self.assertEqual([0.0, 0.0, 0.0], trace[5]["acc"])  # still gated: discarded

    def test_translate_is_immediate_and_ignores_sleep(self) -> None:
        r = self.results["api"]["translateOnSleepingBody"]
        self.assertEqual([1.0, 2.0, 3.0], r["pos"])
        self.assertTrue(r["sleeping"])
        self.assertEqual([0.0, 0.0, 0.0], r["v"])

    def test_wake_only_touches_sleepiness(self) -> None:
        r = self.results["api"]["wakeOnlyTouchesSleepiness"]
        self.assertEqual(100, r["sleepiness"])
        self.assertFalse(r["sleeping"])
        self.assertEqual([0.0, 0.0, 0.0], r["v"])

    def test_sleeping_getter_boundary(self) -> None:
        r = self.results["api"]["sleepingGetter"]
        self.assertFalse(r["beforeAtOne"])
        self.assertTrue(r["atZero"])
        self.assertTrue(r["negative"])

    def test_drag_hook_runs_before_linear_step_only_while_awake(self) -> None:
        r = self.results["api"]["dragHook"]
        self.assertEqual(1, len(r["calls"]))
        self.assertEqual([0.0, 0.0, 0.0], r["calls"][0]["accBefore"])
        self.assertAlmostEqual(1 / 30, r["calls"][0]["dt"], delta=TOLERANCE)
        # 9 m/s^2 for one dt: v.x == 9/30 == 0.3.
        self.assertAlmostEqual(0.3, r["vAfter"][0], delta=TOLERANCE)
        self.assertFalse(self.results["api"]["dragHookSkippedWhileAsleep"])

    def test_has_geometry_flag_follows_box_option(self) -> None:
        r = self.results["api"]["hasGeometryFlag"]
        self.assertTrue(r["withBox"])
        self.assertFalse(r["withoutBox"])

    def test_static_body_is_all_no_ops(self) -> None:
        # briefing body interface: "isStatic: true, mass: 1e12, sleeping:
        # true, no-op adders and tangentSpeed returning zero" -- and
        # position/velocity never move despite the adder calls the harness
        # made before snapshotting.
        r = self.results["api"]["staticBody"]
        self.assertEqual(1e12, r["mass"])
        self.assertTrue(r["isStatic"])
        self.assertTrue(r["sleeping"])
        self.assertEqual([5.0, 6.0, 7.0], r["pos"])
        self.assertEqual([0.0, 0.0, 0.0], r["v"])
        self.assertEqual([0.0, 0.0, 0.0], r["w"])
        self.assertEqual([0.0, 0.0, 0.0], r["tangentSpeedResult"])

    def test_fresh_body_is_born_awake_at_rest_with_no_seeded_gravity(self) -> None:
        r = self.results["api"]["freshBody"]
        self.assertEqual(100, r["sleepiness"])
        self.assertFalse(r["sleeping"])
        self.assertEqual([0.0, 0.0, 0.0], r["v"])
        self.assertEqual([0.0, 0.0, 0.0], r["w"])
        self.assertEqual([0.0, 0.0, 0.0], r["acc"])
        self.assertEqual(1, r["mass"])
        self.assertFalse(r["isStatic"])


if __name__ == "__main__":
    unittest.main()
