<template>
  <div class="wrapped-slide share-slide animate-line-in">
    <div class="slide-header">
      <span class="slide-badge animate-rise-up" style="animation-delay: 0.05s">08 — Share Card</span>
    </div>

    <div class="share-layout">
      <!-- The Card -->
      <div class="share-card animate-wrapped-in" style="animation-delay: 0.15s">
        <div class="card-topbar">
          <span>Player Wrapped 2026</span>
          <span>bfstats.io</span>
        </div>
        <div class="card-body">
          <div class="server-name">{{ data.playerName }}</div>
          <div class="card-subtitle">Battlefield 1942 · Year in Review</div>
          
          <div class="card-grid">
            <div v-for="(stat, idx) in shareStats" :key="idx" class="card-grid-item">
              <div class="card-grid-val" :class="stat.class">{{ stat.value }}</div>
              <div class="card-grid-label">{{ stat.label }}</div>
            </div>
          </div>

          <div class="card-meta-list">
            <div class="meta-row">
              <span class="meta-label">Most Played</span>
              <span class="meta-val">{{ data.favouriteMap.mapName }} · {{ Math.round(data.favouriteMap.winRate * 100) }}% Win</span>
            </div>
            <div class="meta-row">
              <span class="meta-label">Best Moment</span>
              <span class="meta-val">{{ bestMoment.streak }} Kills · {{ bestMoment.mapName }}</span>
            </div>
            <div class="meta-row" v-if="topTeammate !== 'None'">
              <span class="meta-label">Wingman</span>
              <span class="meta-val">{{ topTeammate }}</span>
            </div>
          </div>

          <div class="card-footer">
            <img :src="clippyLogo" alt="" class="card-logo">
            <span class="card-footer-text">Generated by bfstats.io · #PlayerWrapped</span>
          </div>
        </div>
      </div>

      <!-- Actions -->
      <div class="share-actions animate-rise-up" style="animation-delay: 0.35s">
        <div class="buttons-row">
          <button 
            class="action-btn" 
            :style="{ backgroundColor: copyBg, borderColor: copyBg, color: copyInk }" 
            @click="copyShareMessage"
          >
            {{ copyLabel }}
          </button>
          <button class="action-btn action-btn-outline" @click="$emit('restart')">Replay from Intro</button>
        </div>
        <div class="actions-note">Card renders at 1080×1350 for stories.</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import type { PlayerWrappedData } from '@/services/wrappedService'
import clippyLogo from '@/assets/clippy_my_boi.webp'

const props = defineProps<{
  data: PlayerWrappedData
}>()

defineEmits<{
  (e: 'restart'): void
}>()

const copied = ref(false)

const shareStats = computed(() => [
  { value: props.data.yearInNumbers.totalKills.toLocaleString(), label: 'Kills', class: '' },
  { value: props.data.yearInNumbers.kdRatio.toFixed(2), label: 'K/D Ratio', class: 'kd-accent' },
  { value: props.data.medals.killStreaks25.toLocaleString(), label: 'Streaks 25+', class: '' },
  { value: `#${props.data.yearInNumbers.serverRank.toLocaleString()}`, label: 'Server Rank', class: 'rank-accent' }
])

const topTeammate = computed(() => {
  const squad = props.data.squad
  return squad && squad.length > 0 ? squad[0].name : 'None'
})

const bestMoment = computed(() => {
  if (!props.data.bestMoments || props.data.bestMoments.length === 0) {
    return { streak: 0, mapName: 'None', date: '', estimatedDurationMinutes: 0, serverStreakRank: 0 }
  }
  const streak = props.data.bestMoments.find(m => m.type === 'streak')
  if (streak) {
    return {
      streak: streak.value,
      mapName: streak.mapName,
      date: streak.date,
      estimatedDurationMinutes: streak.estimatedDurationMinutes,
      serverStreakRank: streak.serverStreakRank
    }
  }
  const first = props.data.bestMoments[0]
  return {
    streak: first.value,
    mapName: first.mapName,
    date: first.date,
    estimatedDurationMinutes: first.estimatedDurationMinutes,
    serverStreakRank: first.serverStreakRank
  }
})

const copyLabel = computed(() => copied.value ? 'Copied summary!' : 'Copy Summary Text ↗')
const copyBg = computed(() => copied.value ? 'var(--mm-accent)' : 'transparent')
const copyInk = computed(() => copied.value ? '#000' : 'var(--mm-ink)')

function copyShareMessage() {
  const msg = `🎮 2026 Player Wrapped for ${props.data.playerName} 🎮\n` +
              `• Server Rank: #${props.data.yearInNumbers.serverRank.toLocaleString()}\n` +
              `• Total Kills: ${props.data.yearInNumbers.totalKills.toLocaleString()}\n` +
              `• K/D Ratio: ${props.data.yearInNumbers.kdRatio.toFixed(2)}\n` +
              `• Favorite Map: ${props.data.favouriteMap.mapName} (${Math.round(props.data.favouriteMap.winRate * 100)}% Win)\n` +
              `• Best Moment: ${bestMoment.value.streak} Kill Streak on ${bestMoment.value.mapName}\n` +
              `Check the full year in review stats at bfstats.io! #PlayerWrapped`

  navigator.clipboard.writeText(msg).then(() => {
    copied.value = true
    setTimeout(() => { copied.value = false }, 2000)
  })
}
</script>

<style scoped>

.wrapped-slide {
  width: 100%;
  display: flex;
  flex-direction: column;
  box-sizing: border-box;
}

.slide-header {
  margin-bottom: 24px;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 8px;
}

.slide-badge {
  font-family: var(--mm-font-mono);
  font-size: 10px;
  letter-spacing: 0.2em;
  color: var(--mm-ink-muted);
  text-transform: uppercase;
}

.slide-title {
  font-family: var(--mm-font-display);
  font-size: 38px;
  font-weight: 300;
  letter-spacing: -0.02em;
  color: var(--mm-ink);
  margin: 0;
}

.share-layout {
  display: flex;
  gap: 44px;
  align-items: flex-start;
  flex-wrap: wrap;
  width: 100%;
}

.share-card {
  width: 440px;
  max-width: 100%;
  border: 1px solid var(--mm-rule-strong);
  border-radius: 2px;
  overflow: hidden;
  background-color: var(--mm-bg);
  box-sizing: border-box;
}

.card-topbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 18px;
  background-color: var(--mm-highlight, var(--mm-bg-soft));
  color: var(--mm-highlight-ink, var(--mm-ink));
  font-family: var(--mm-font-mono);
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.16em;
  text-transform: uppercase;
}

.card-body {
  padding: 26px 22px 24px;
}

.server-name {
  font-family: var(--mm-font-display);
  font-size: 20px;
  font-weight: 600;
  color: var(--mm-ink);
  text-align: left;
}

.card-subtitle {
  margin-top: 3px;
  font-family: var(--mm-font-mono);
  font-size: 11px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--mm-ink-muted);
  text-align: left;
}

.card-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1px;
  background-color: var(--mm-rule);
  border: 1px solid var(--mm-rule);
  margin-top: 22px;
}

.card-grid-item {
  background-color: var(--mm-bg);
  padding: 16px;
  text-align: left;
}

.card-grid-val {
  font-family: var(--mm-font-display);
  font-weight: 300;
  font-size: 30px;
  line-height: 1;
  color: var(--mm-ink);
}

.card-grid-label {
  margin-top: 8px;
  font-family: var(--mm-font-mono);
  font-size: 10px;
  letter-spacing: 0.13em;
  text-transform: uppercase;
  color: var(--mm-ink-muted);
}

.card-meta-list {
  margin-top: 20px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.meta-row {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 12px;
  font-family: var(--mm-font-mono);
  font-size: 11px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.meta-label {
  color: var(--mm-ink-muted);
}

.meta-val {
  color: var(--mm-ink);
}

.kd-accent {
  color: var(--mm-kd-good, #b4c060);
}

.rank-accent {
  color: var(--mm-accent-soft, #7da34c);
}

.card-footer {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-top: 22px;
  padding-top: 16px;
  border-top: 1px solid var(--mm-rule);
}

.card-logo {
  width: 26px;
  height: 26px;
  object-fit: contain;
}

.card-footer-text {
  font-family: var(--mm-font-mono);
  font-size: 10px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--mm-ink-muted);
}

.share-actions {
  flex: 1;
  min-width: 240px;
  padding-top: 6px;
  text-align: left;
}

.actions-desc {
  margin: 0 0 22px;
  font-family: var(--mm-font-display);
  font-size: 15px;
  color: var(--mm-ink-soft);
  max-width: 360px;
  line-height: 1.5;
}

.buttons-row {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
}

.action-btn {
  background: none;
  border: 1px solid var(--mm-rule-strong);
  color: var(--mm-ink);
  font-family: var(--mm-font-mono);
  font-size: 11px;
  letter-spacing: 0.08em;
  padding: 10px 16px;
  border-radius: var(--mm-radius-sm, 2px);
  cursor: pointer;
  transition: all 0.25s ease;
}

.action-btn:hover {
  border-color: var(--mm-accent);
}

.action-btn-outline {
  border-color: var(--mm-rule);
  color: var(--mm-ink-soft);
}

.action-btn-outline:hover {
  border-color: var(--mm-rule-strong);
  color: var(--mm-ink);
}

.actions-note {
  margin-top: 28px;
  font-family: var(--mm-font-mono);
  font-size: 10.5px;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color: var(--mm-ink-faint);
}

@media (max-width: 768px) {
  .share-layout {
    gap: 24px;
  }
}
</style>
