<template>
  <div class="wrapped-slide share-slide animate-line-in">
    <div class="slide-header">
      <span class="slide-badge animate-rise-up" style="animation-delay: 0.05s">08 — Share Card</span>
      <h2 class="slide-title animate-rise-up" style="animation-delay: 0.1s">Take it with you.</h2>
    </div>

    <div class="share-layout">
      <!-- The Card -->
      <div class="share-card animate-wrapped-in" style="animation-delay: 0.15s">
        <div class="card-topbar">
          <span>Server Wrapped 2026</span>
          <span>bfstats.io</span>
        </div>
        <div class="card-body">
          <div class="server-name">{{ data.serverName }}</div>
          <div class="card-subtitle">Battlefield 1942 · Year in Review</div>
          
          <div class="card-grid">
            <div v-for="(stat, idx) in shareStats" :key="idx" class="card-grid-item">
              <div class="card-grid-val">{{ stat.value }}</div>
              <div class="card-grid-label">{{ stat.label }}</div>
            </div>
          </div>

          <div class="card-meta-list">
            <div class="meta-row">
              <span class="meta-label">Most Played</span>
              <span class="meta-val">{{ data.rotation.mostPlayedMapName }}</span>
            </div>
            <div class="meta-row">
              <span class="meta-label">Top Gun</span>
              <span class="meta-val">{{ topKDPlayerName }} · <span class="kd-accent">{{ topKDPlayerRatio }} K/D</span></span>
            </div>
            <div class="meta-row">
              <span class="meta-label">Peak Population</span>
              <span class="meta-val">{{ data.yearInNumbers.peakPopulation }} · {{ peakDateFormatted }}</span>
            </div>
          </div>

          <div class="card-footer">
            <img :src="clippyLogo" alt="" class="card-logo">
            <span class="card-footer-text">Generated by bfstats.io · #ServerWrapped</span>
          </div>
        </div>
      </div>

      <!-- Actions -->
      <div class="share-actions animate-rise-up" style="animation-delay: 0.35s">
        <p class="actions-desc">One card, the whole year. Post it, pin it, or send it to the squad who never showed up to the closest battles.</p>
        <div class="buttons-row">
          <button 
            class="action-btn" 
            :style="{ backgroundColor: copyBg, borderColor: copyBg, color: copyInk }" 
            @click="copyShareMessage"
          >
            {{ copyLabel }}
          </button>
          <button class="action-btn action-btn-outline" @click="$emit('restart')">Replay from Intro</button>
        </div>
        <div class="actions-note">Card renders at 1080×1350 for stories.</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import type { ServerWrappedData } from '@/services/wrappedService'
import clippyLogo from '@/assets/clippy_my_boi.webp'

const props = defineProps<{
  data: ServerWrappedData
}>()

defineEmits<{
  (e: 'restart'): void
}>()

const copied = ref(false)

const shareStats = computed(() => [
  { value: props.data.yearInNumbers.roundsFought.toLocaleString(), label: 'Rounds' },
  { value: props.data.yearInNumbers.uniqueSoldiers.toLocaleString(), label: 'Soldiers' },
  { value: Math.round(props.data.yearInNumbers.hoursInCombat).toLocaleString(), label: 'Hours' },
  { value: props.data.yearInNumbers.totalDecorations.toLocaleString(), label: 'Medals' }
])

const topKDPlayerName = computed(() => {
  const list = props.data.honours.topKDRatios
  return list && list.length > 0 ? list[0].playerName : 'None'
})

const topKDPlayerRatio = computed(() => {
  const list = props.data.honours.topKDRatios
  return list && list.length > 0 ? list[0].kdRatio.toFixed(2) : '0.00'
})

const peakDateFormatted = computed(() => {
  const ts = props.data.yearInNumbers.peakTimestamp
  if (!ts) return ''
  const date = new Date(ts)
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
})

const highestStreakCount = computed(() => {
  if (props.data.decorations.streakOfTheYear) {
    return props.data.decorations.streakOfTheYear.streak
  }
  return props.data.decorations.mostStreaksOf25.value > 0 ? 25 : 0
})

const copyLabel = computed(() => copied.value ? 'Copied summary!' : 'Copy Summary Text ↗')
const copyBg = computed(() => copied.value ? 'var(--mm-accent)' : 'transparent')
const copyInk = computed(() => copied.value ? '#000' : 'var(--mm-ink)')

function copyShareMessage() {
  const msg = `🎮 2026 Server Wrapped for ${props.data.serverName} 🎮\n` +
              `• Rounds Fought: ${props.data.yearInNumbers.roundsFought.toLocaleString()}\n` +
              `• Hours in Combat: ${Math.round(props.data.yearInNumbers.hoursInCombat).toLocaleString()}h\n` +
              `• Most Played Map: ${props.data.rotation.mostPlayedMapName}\n` +
              `• Top K/D Player: ${topKDPlayerName.value}\n` +
              `• Highest Kill Streak: ${highestStreakCount.value} kills\n` +
              `Check the full year in review stats at bfstats.io! #ServerWrapped`

  navigator.clipboard.writeText(msg).then(() => {
    copied.value = true
    setTimeout(() => { copied.value = false }, 2000)
  })
}
</script>

<style scoped>
.wrapped-slide {
  width: 100%;
  display: flex;
  flex-direction: column;
  box-sizing: border-box;
}

.slide-header {
  margin-bottom: 24px;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 8px;
}

.slide-badge {
  font-family: var(--mm-font-mono);
  font-size: 10px;
  letter-spacing: 0.2em;
  color: var(--mm-ink-muted);
  text-transform: uppercase;
}

.slide-title {
  font-family: var(--mm-font-display);
  font-size: 38px;
  font-weight: 300;
  letter-spacing: -0.02em;
  color: var(--mm-ink);
  margin: 0;
}

.share-layout {
  display: flex;
  gap: 44px;
  align-items: flex-start;
  flex-wrap: wrap;
  width: 100%;
}

.share-card {
  width: 440px;
  max-width: 100%;
  border: 1px solid var(--mm-rule-strong);
  border-radius: 2px;
  overflow: hidden;
  background-color: var(--mm-bg);
  box-sizing: border-box;
}

.card-topbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 18px;
  background-color: var(--mm-highlight, var(--mm-bg-soft));
  color: var(--mm-highlight-ink, var(--mm-ink));
  font-family: var(--mm-font-mono);
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.16em;
  text-transform: uppercase;
}

.card-body {
  padding: 26px 22px 24px;
}

.server-name {
  font-family: var(--mm-font-display);
  font-size: 20px;
  font-weight: 600;
  color: var(--mm-ink);
  text-align: left;
}

.card-subtitle {
  margin-top: 3px;
  font-family: var(--mm-font-mono);
  font-size: 11px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--mm-ink-muted);
  text-align: left;
}

.card-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1px;
  background-color: var(--mm-rule);
  border: 1px solid var(--mm-rule);
  margin-top: 22px;
}

.card-grid-item {
  background-color: var(--mm-bg);
  padding: 16px;
  text-align: left;
}

.card-grid-val {
  font-family: var(--mm-font-display);
  font-weight: 300;
  font-size: 30px;
  line-height: 1;
  color: var(--mm-ink);
}

.card-grid-label {
  margin-top: 8px;
  font-family: var(--mm-font-mono);
  font-size: 10px;
  letter-spacing: 0.13em;
  text-transform: uppercase;
  color: var(--mm-ink-muted);
}

.card-meta-list {
  margin-top: 20px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.meta-row {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 12px;
  font-family: var(--mm-font-mono);
  font-size: 11px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.meta-label {
  color: var(--mm-ink-muted);
}

.meta-val {
  color: var(--mm-ink);
}

.kd-accent {
  color: var(--mm-kd-good, #b4c060);
}

.card-footer {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-top: 22px;
  padding-top: 16px;
  border-top: 1px solid var(--mm-rule);
}

.card-logo {
  width: 26px;
  height: 26px;
  object-fit: contain;
}

.card-footer-text {
  font-family: var(--mm-font-mono);
  font-size: 10px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--mm-ink-muted);
}

.share-actions {
  flex: 1;
  min-width: 240px;
  padding-top: 6px;
  text-align: left;
}

.actions-desc {
  margin: 0 0 22px;
  font-family: var(--mm-font-display);
  font-size: 15px;
  color: var(--mm-ink-soft);
  max-width: 360px;
  line-height: 1.5;
}

.buttons-row {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
}

.action-btn {
  background: none;
  border: 1px solid var(--mm-rule-strong);
  color: var(--mm-ink);
  font-family: var(--mm-font-mono);
  font-size: 11px;
  letter-spacing: 0.08em;
  padding: 10px 16px;
  border-radius: var(--mm-radius-sm, 2px);
  cursor: pointer;
  transition: all 0.25s ease;
}

.action-btn:hover {
  border-color: var(--mm-accent);
}

.action-btn-outline {
  border-color: var(--mm-rule);
  color: var(--mm-ink-soft);
}

.action-btn-outline:hover {
  border-color: var(--mm-rule-strong);
  color: var(--mm-ink);
}

.actions-note {
  margin-top: 28px;
  font-family: var(--mm-font-mono);
  font-size: 10.5px;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color: var(--mm-ink-faint);
}

@media (max-width: 1023px) {
  .share-layout {
    gap: 24px;
  }
  
  .actions-desc,
  .actions-note {
    display: none !important;
  }
  
  .share-actions {
    padding-top: 0;
    width: 100%;
  }
  
  .buttons-row {
    display: flex;
    width: 100%;
    gap: 10px;
  }
  
  .action-btn {
    flex: 1;
    text-align: center;
    justify-content: center;
    padding: 10px 8px !important;
  }
}
</style>
