{
 "title": "site stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId" }
  ]
 },
 "panels": [
  {
   "title": "Data Explorer Views",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"junie-des-1942stats\"} | json | logfmt | Path=~\"/stats/data-explorer/.*\" [1m]))"
    }
   ]
  },
  {
   "title": "[ Players Page ]",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"junie-des-1942stats\"}\n  | json\n  | route_type=\"player_page\"\n  | SourceContext = \"Microsoft.AspNetCore.Hosting.Diagnostics\"\n  | ElapsedMilliseconds != \"\"\n  | RequestPath !~ \".*search.*\"\n  | label_format RequestPath=\"{{.RequestPath}}\", ElapsedMs=\"{{.ElapsedMilliseconds}}\", TraceId=\"{{.TraceId}}\", ClientIP=\"{{.client_ip}}\", Browser=\"{{.browser}}\", IsBot=\"{{.is_bot}}\",\n  UserAgent=\"{{.user_agent_original}}\"\n"
    }
   ]
  },
  {
   "title": "Trace",
   "type": "traces",
   "gridPos": { "h": 30, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "query": "${traceId:raw}", "tableType": "traces" }
   ]
  },
  {
   "title": "[ Server Page ]",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"junie-des-1942stats\"}\n  | json\n  | route_type=\"server_page\"\n  | SourceContext = \"Microsoft.AspNetCore.Hosting.Diagnostics\"\n  | ElapsedMilliseconds != \"\"\n  | RequestPath !~ \"/stats/servers/rankings\"  \n  | label_format RequestPath=\"{{.RequestPath}}\", ElapsedMs=\"{{.ElapsedMilliseconds}}\", TraceId=\"{{.TraceId}}\", ClientIP=\"{{.client_ip}}\", Browser=\"{{.browser}}\", IsBot=\"{{.is_bot}}\",\n  UserAgent=\"{{.user_agent_original}}\"\n"
    }
   ]
  }
 ]
}