#!/usr/bin/env python3
"""Bake the game's shipped control maps into `viewer/controls-defaults.js`.

The viewer's default bindings are the game's own data, not a table this repo
invents: this script reads the shipped control maps out of a real install and
embeds the four `.con` sources verbatim into an ES module. `viewer/controls.js`
parses them with the same parser it applies to an imported player profile, so
there is exactly one binding grammar in the codebase.

    python3 extract_profile_controls.py [--controls-dir DIR] [-o viewer/controls-defaults.js]

The default controls dir is the Wine install the owner's profile lives in
(`~/.wine/drive_c/EA Games/Battlefield 1942/Mods/bf1942/Settings/Default/Controls`).
The generated module is committed, so this only needs re-running when the
shipped maps are re-extracted.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

DEFAULT_CONTROLS_DIR = (
    Path.home() / ".wine/drive_c/EA Games/Battlefield 1942"
    / "Mods/bf1942/Settings/Default/Controls"
)

# The four files a profile's Controls/ folder carries. Common carries the
# game-input map (c_GI*) and the common player triggers; the other three are
# the context maps (on foot, aircraft, land & sea).
CONTROL_FILES = ["Common.con", "Infantry.con", "Air.con", "Land.con"]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--controls-dir", default=str(DEFAULT_CONTROLS_DIR))
    ap.add_argument("-o", "--out",
                    default=str(Path(__file__).resolve().parent / "viewer/controls-defaults.js"))
    args = ap.parse_args()

    src = Path(args.controls_dir)
    missing = [n for n in CONTROL_FILES if not (src / n).is_file()]
    if missing:
        raise SystemExit(
            f"{src} is missing {', '.join(missing)} — pass --controls-dir "
            "pointing at a BF1942 install's Settings/Default/Controls")

    files = {name[:-4].lower(): (src / name).read_text() for name in CONTROL_FILES}

    module = (
        "// Generated by tools/bf1942-models/extract_profile_controls.py from\n"
        "// Mods/bf1942/Settings/Default/Controls/ — the game's own shipped\n"
        "// control maps, verbatim. Do not edit by hand: re-run the script\n"
        "// (it needs the game data) to refresh.\n"
        "export const CONTROLS_DEFAULTS = "
        + json.dumps({"source": "Mods/bf1942/Settings/Default/Controls",
                      "files": files}, indent=2)
        + ";\n"
    )
    Path(args.out).write_text(module)
    print(f"wrote {args.out} from {src}")


if __name__ == "__main__":
    main()
