/* The mod selector, shared by the three viewer pages.
 *
 * Vanilla BF1942 keeps the asset tree it has always had — `models/`, `maps/`,
 * `models/poses/` — because that tree is already published. A mod lives in a
 * sibling subtree, `models/mods/<id>/` and `maps/mods/<id>/`, each holding its
 * own `models.json` / `maps.json` / `poses-matrix.json` written by the same
 * extractor that writes vanilla's. `models/mods.json` is the index over both
 * roots, generated by `build_mods_manifest.py`.
 *
 * It lives inside `models/` rather than at the viewer root because that is the
 * half of the tree that is a PVC mount. The mesh image bakes in everything
 * under `viewer/` except `models/` and `maps/`, which the Deployment replaces
 * with subPath mounts — so a registry at the root could only change on an image
 * build, while what it describes changes on an upload.
 *
 * So a page does not learn about mods; it learns one base path:
 *
 *     const mod = await selectMod('models');
 *     const MODELS_BASE = mod.paths.models;   // 'models' | 'models/mods/eod'
 *
 * and every asset URL it already builds keeps working, one directory deeper.
 *
 * Three things this has to survive, because production will hit all three:
 *
 * 1. No `models/mods.json` at all (a tree uploaded before this existed). The
 *    fetch fails, vanilla's classic paths are returned, and no picker is drawn.
 * 2. A mod present on one tab and not another — EoD models uploaded, EoD maps
 *    not yet. The per-tab `counts` decide, so the Maps picker simply does not
 *    offer EoD until `maps/mods/eod/maps.json` exists.
 * 3. A `?mod=` for something this tab cannot serve. Falls back to vanilla
 *    rather than fetching a manifest that 404s.
 *
 * The choice lives in `?mod=` so a link carries it, and in localStorage so
 * moving between tabs keeps it. Changing it reloads the page: all three pages
 * resolve their manifest once at module scope with top-level await, and a
 * reload is both the honest way to re-enter that and how a static viewer with
 * no router ought to behave.
 */

const STORE_KEY = 'bf42-mesh-mod';
const VANILLA = {
  id: 'bf1942',
  name: 'Battlefield 1942',
  short: 'BF1942',
  paths: { models: 'models', maps: 'maps', poses: 'models/poses' },
  counts: { models: 1, maps: 1, poses: 1 },
};

function stored() {
  try { return localStorage.getItem(STORE_KEY); } catch { return null; }
}

function remember(id) {
  try {
    if (id === VANILLA.id) localStorage.removeItem(STORE_KEY);
    else localStorage.setItem(STORE_KEY, id);
  } catch { /* private mode; the ?mod= in the URL still carries the choice */ }
}

export async function loadMods() {
  try {
    const response = await fetch(`models/mods.json?t=${Date.now()}`);
    if (!response.ok) throw new Error(String(response.status));
    const data = await response.json();
    const mods = Array.isArray(data) ? data : data?.mods;
    if (!Array.isArray(mods) || !mods.length) return [VANILLA];
    // Vanilla is the floor: if the registry somehow omits it, the pages still
    // need a base path to fall back to.
    return mods.some(m => m.id === VANILLA.id) ? mods : [VANILLA, ...mods];
  } catch {
    return [VANILLA];
  }
}

/** Mods with at least one asset on this tab, vanilla always first. */
function servable(mods, tab) {
  return mods.filter(mod =>
    mod.id === VANILLA.id || Number(mod?.counts?.[tab] || 0) > 0);
}

function withMod(href, id) {
  const url = new URL(href, location.href);
  if (id === VANILLA.id) url.searchParams.delete('mod');
  else url.searchParams.set('mod', id);
  return url.pathname + url.search;
}

function install(available, active, tab) {
  const nav = document.querySelector('.shell-nav');
  if (!nav) return;

  // Carry the mod across a tab change, so a shared Models link lands on the
  // same mod's Maps.
  for (const link of nav.querySelectorAll('.shell-tabs a[href]')) {
    link.href = withMod(link.getAttribute('href'), active.id);
  }

  // One mod to choose from is not a choice. Nothing is drawn, which is also
  // what production looks like until a mod's assets are uploaded.
  if (available.length < 2) return;

  let slot = nav.querySelector('.shell-mods');
  if (!slot) {
    slot = document.createElement('span');
    slot.className = 'shell-mods';
    const sub = nav.querySelector('.shell-sub');
    if (sub) nav.insertBefore(slot, sub);
    else nav.appendChild(slot);
  }
  slot.textContent = '';

  const label = document.createElement('label');
  label.className = 'shell-mods-label';
  label.setAttribute('for', 'shell-mod-select');
  label.textContent = 'Mod';

  const select = document.createElement('select');
  select.id = 'shell-mod-select';
  select.title = 'Which game or mod to browse';
  for (const mod of available) {
    const option = new Option(mod.short || mod.name || mod.id, mod.id);
    option.title = `${mod.name} — ${mod.counts?.[tab] || 0} on this tab`;
    select.appendChild(option);
  }
  select.value = active.id;
  select.addEventListener('change', () => {
    remember(select.value);
    location.href = withMod(location.href, select.value);
  });

  slot.append(label, select);
}

/**
 * Resolve the mod this page should serve, and draw the picker for `tab`
 * ('models' | 'maps' | 'poses'). Returns the mod record; read its
 * `paths[tab]` for the base every asset URL hangs off.
 */
export async function selectMod(tab) {
  const available = servable(await loadMods(), tab);
  const wanted = (new URLSearchParams(location.search).get('mod')
    || stored() || VANILLA.id).toLowerCase();
  const active = available.find(mod => mod.id === wanted) || available[0];
  // A ?mod= that this tab cannot serve must not stick for the next tab either.
  if (active.id === wanted) remember(active.id);
  install(available, active, tab);
  return active;
}
